# Docker instances are configured inside the docker.yaml file. 
# Both IP:PORT and Socket connections are supported.
# 
# For IP:PORT, simply make sure your Docker instance has been configured 
# to accept API traffic over the HTTP API.
# https://gist.github.com/styblope/dc55e0ad2a9848f2cc3307d4819d819f
#
# The following only covers unsecure HTTP connection.
# For secure TLS connection, please refer to the official documentation:
# https://gethomepage.dev/en/configs/docker/ 
# and 
# https://docs.docker.com/engine/security/protect-access/
#
# ======================================================================
#
# Please modify the following according to your setup; you can add multiple blocks :
# my-local-docker:
#  host: 1.2.3.4
#  port: 2375