title: ENSG Mini-SDI
theme: dark # or light
color: slate
# Supported colors are: slate, gray, zinc, neutral, stone, amber, yellow, lime, green,
#emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
iconStyle: theme # optional, defaults to gradient
headerStyle: boxed # or clean
base: http://hub.ensg-sdi.docker
language: fr
target: _blank # Possible options include _blank, _self, and _top
# You can use the ‘Quick Launch’ feature to search services, perform a web search or open a URL.
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: true
hideVersion: true
showStats: true
# Hide the visible API error messages either globally in settings.yaml
hideErrors: true
