#
# First come the information widgets section
#
# >> Complete doc at : https://gethomepage.dev/en/configs/widgets/
- resources:
    cpu: true
    memory: true
    disk: /

# No registration is required at all! See https://open-meteo.com/en/docs
# You can optionally not pass a latitude and longitude and the widget will use
# your current location (requires a secure context, eg. HTTPS).
- openmeteo:
    label: Issy-les-Moulineaux # optional
    latitude: 48.82
    longitude: 2.28
    timezone: Europe/Paris # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- search:
    provider: google # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank # One of _self, _blank, _parent or _top

